### ISSUE TITLE
ASDF on host?

### ISSUE THREAD

**Issue by HerrNaN** [sidusIO/sediment#12]
Should we have [asdf](https://asdf-vm.com/) on the host system

**Comment by HerrNaN** [comment]
The merged solution does not translate well into distroboxes since most of the actual code running lives on the host system-space.

Suggestion is to install asdf with a just-script instead since we then can install it in user-space

**Comment by williamleven** [comment]
Suggestion sounds good. Alternative could be to symlink asdf into userspace.

**Comment by HerrNaN** [comment]
Yes, I agree. Nonetheless, this still has to be done post-install since user-space doesn't exist built time. 

Keeping the installation as one chunk, in a justfile, instead of both in image and justfile sounds like the most sound approach to me.
